{{- if .Values.elasticsearch.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}-elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goapp-stack.labels" . | nindent 4 }}
spec:
  version: {{ .Values.elasticsearch.version }}
  nodeSets:
    - name: default
      count: {{ .Values.elasticsearch.nodes }}
      config:
        {{- toYaml .Values.elasticsearch.config | nindent 8 }}
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              {{- with .Values.elasticsearch.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.elasticsearch.storage.size }}
            storageClassName: {{ .Values.global.storageClass }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
{{- end }}
