apiVersion: v1
kind: Service
metadata:
  name: {{ include "goapp-stack.goapp.serviceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goapp-stack.labels" . | nindent 4 }}
    app: fileshare
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.goapp.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.goapp.http3.enabled }}
    - port: {{ .Values.goapp.port }}
      targetPort: http3
      protocol: UDP
      name: http3
    {{- end }}
  selector:
    app: fileshare
    {{- include "goapp-stack.selectorLabels" . | nindent 4 }}
