apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-goapp
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "goapp-stack.labels" . | nindent 4 }}
automountServiceAccountToken: false
