apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-twitter
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: twitter-clone
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
