apiVersion: v2
name: twitter-stack
description: Twitter Clone - Microservices Application Stack
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - twitter
  - microservices
  - go
  - kubernetes
maintainers:
  - name: alexprut
